### ISSUE TITLE
Update InvocationContext to provide a standard accessor for interceptor bindings

### ISSUE THREAD

**Issue by starksm64** [jakartaee/interceptors#100]
This was brought up in the CDI project as the following issue:
https://github.com/jakartaee/cdi/issues/592

The basic idea is to add a series of getInterceptorBindings() default methods to the jakarta.interceptors.InvocationContext interface.

**Comment by mkouba** [comment]
@Ladicek I believe that this was fixed in https://github.com/jakartaee/interceptors/pull/99, or?

**Comment by Ladicek** [comment]
That is correct. I unfortunately didn't link this issue in my PR, and I don't have commit powers in Jakarta Interceptors, but this is done.
